CREATE TABLE Task (
    id MEDIUMINT UNIQUE NOT NULL AUTO_INCREMENT,
    userID INT(12) NOT NULL,
    title VARCHAR(125) NOT NULL,
    description VARCHAR(255) NOT NULL,
    status ENUM('PENDING', 'IN_WORK', 'COMPLETED', 'ARCHIVED') NOT NULL DEFAULT 'PENDING',
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    taskEndsAt TIMESTAMP(6),
    PRIMARY KEY (id),
    FOREIGN KEY (userID) REFERENCES User(id)
);